### ISSUE TITLE
Token data update failure

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin-website#578]
Token data is stale according to Kay.   While investigating this, I saw the following in the logs.  Perhaps this is preventing updates of token data.

    Traceback (most recent call last):
      File "logic/scripts/update_token_insight.py", line 442, in <module>
        token_stats.compute_ogn_stats()
      File "/app/logic/scripts/token_stats.py", line 280, in compute_ogn_stats
        ogn_staked_data = fetch_onchain_staking_stats_by_duration()
      File "/app/logic/scripts/token_stats.py", line 92, in fetch_onchain_staking_stats_by_duration
        response = raw_json.json()
      File "/app/.heroku/python/lib/python2.7/site-packages/requests/models.py", line 897, in json
        return complexjson.loads(self.text, **kwargs)
      File "/app/.heroku/python/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/app/.heroku/python/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/app/.heroku/python/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

The README has an example for `./logic/scripts/token_stats.py`, but that script is not being run with task scheduler on heroku.  Not clear yet if that's related.

**Comment by mikeshultz** [comment]
Ended up being the analytics API endpoint throwing a 500.  These API calls should probably handle without crashing at a minimum.  Repurposing this issue.
