### ISSUE TITLE
Video serve error

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin-website#597]
Seen in logs after upgrade:

    2021-04-30T17:44:48.409940+00:00 app[web.2]: [2021-04-30 10:44:48,399] ERROR in app: Exception on /ko/video/steve-chen-youtube-founder [GET]
    2021-04-30T17:44:48.409958+00:00 app[web.2]: Traceback (most recent call last):
    2021-04-30T17:44:48.409958+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    2021-04-30T17:44:48.409959+00:00 app[web.2]: response = self.full_dispatch_request()
    2021-04-30T17:44:48.409959+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    2021-04-30T17:44:48.409960+00:00 app[web.2]: rv = self.handle_user_exception(e)
    2021-04-30T17:44:48.409960+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    2021-04-30T17:44:48.409961+00:00 app[web.2]: return cors_after_request(app.make_response(f(*args, **kwargs)))
    2021-04-30T17:44:48.409965+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/hooks/framework_flask.py", line 111, in _nr_wrapper_Flask_handle_exception_
    2021-04-30T17:44:48.409966+00:00 app[web.2]: return wrapped(*args, **kwargs)
    2021-04-30T17:44:48.409966+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    2021-04-30T17:44:48.409967+00:00 app[web.2]: reraise(exc_type, exc_value, tb)
    2021-04-30T17:44:48.409967+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    2021-04-30T17:44:48.409968+00:00 app[web.2]: raise value
    2021-04-30T17:44:48.409968+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    2021-04-30T17:44:48.409969+00:00 app[web.2]: rv = self.dispatch_request()
    2021-04-30T17:44:48.409969+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    2021-04-30T17:44:48.409970+00:00 app[web.2]: return self.view_functions[rule.endpoint](**req.view_args)
    2021-04-30T17:44:48.409971+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/hooks/framework_flask.py", line 50, in _nr_wrapper_handler_
    2021-04-30T17:44:48.409971+00:00 app[web.2]: return wrapped(*args, **kwargs)
    2021-04-30T17:44:48.409972+00:00 app[web.2]: File "/app/views/web_views.py", line 502, in video
    2021-04-30T17:44:48.409972+00:00 app[web.2]: if len(videoList) == 0:
    2021-04-30T17:44:48.409973+00:00 app[web.2]: TypeError: object of type 'filter' has no len()

**Comment by mikeshultz** [comment]
Fixed by e127ec4
