### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#623]
https://www.originprotocol.com/ru and https://www.originprotocol.com/hr and https://www.originprotocol.com/he and https://www.originprotocol.com/ar are throwing 500 errors ~~and other languages have some metadata showing up in the body of the homepage~~ (fixed https://github.com/OriginProtocol/origin-website/commit/8326653214cb06429432fe42f8ebd4b61302c782).

https://www.loom.com/share/5a89e9b69cb041d58ebaa2ed7545c47d

```bash
2022-05-01T17:20:27.581310+00:00 app[web.3]: [2022-05-01 10:20:27,578] ERROR in app: Exception on /ru/ [GET]
2022-05-01T17:20:27.581321+00:00 app[web.3]: Traceback (most recent call last):
2022-05-01T17:20:27.581322+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
2022-05-01T17:20:27.581323+00:00 app[web.3]:     response = self.full_dispatch_request()
2022-05-01T17:20:27.581324+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
2022-05-01T17:20:27.581324+00:00 app[web.3]:     rv = self.handle_user_exception(e)
2022-05-01T17:20:27.581325+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
2022-05-01T17:20:27.581325+00:00 app[web.3]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
2022-05-01T17:20:27.581326+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/hooks/framework_flask.py", line 122, in _nr_wrapper_Flask_handle_exception_
2022-05-01T17:20:27.581327+00:00 app[web.3]:     return wrapped(*args, **kwargs)
2022-05-01T17:20:27.581327+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
2022-05-01T17:20:27.581327+00:00 app[web.3]:     reraise(exc_type, exc_value, tb)
2022-05-01T17:20:27.581328+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
2022-05-01T17:20:27.581329+00:00 app[web.3]:     raise value
2022-05-01T17:20:27.581330+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
2022-05-01T17:20:27.581331+00:00 app[web.3]:     rv = self.dispatch_request()
2022-05-01T17:20:27.581331+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
2022-05-01T17:20:27.581331+00:00 app[web.3]:     return self.view_functions[rule.endpoint](**req.view_args)
2022-05-01T17:20:27.581332+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/hooks/framework_flask.py", line 60, in _nr_wrapper_handler_
2022-05-01T17:20:27.581333+00:00 app[web.3]:     return wrapped(*args, **kwargs)
2022-05-01T17:20:27.581333+00:00 app[web.3]:   File "/app/views/web_views.py", line 147, in index
2022-05-01T17:20:27.581334+00:00 app[web.3]:     return render_template(
2022-05-01T17:20:27.581334+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/api/function_trace.py", line 163, in literal_wrapper
2022-05-01T17:20:27.581335+00:00 app[web.3]:     return wrapped(*args, **kwargs)
2022-05-01T17:20:27.581335+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
2022-05-01T17:20:27.581335+00:00 app[web.3]:     return _render(
2022-05-01T17:20:27.581336+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
2022-05-01T17:20:27.581336+00:00 app[web.3]:     rv = template.render(context)
2022-05-01T17:20:27.581336+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/api/function_trace.py", line 143, in dynamic_wrapper
2022-05-01T17:20:27.581337+00:00 app[web.3]:     return wrapped(*args, **kwargs)
2022-05-01T17:20:27.581337+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
2022-05-01T17:20:27.581337+00:00 app[web.3]:     self.environment.handle_exception()
2022-05-01T17:20:27.581338+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
2022-05-01T17:20:27.581338+00:00 app[web.3]:     reraise(*rewrite_traceback_stack(source=source))
2022-05-01T17:20:27.581338+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
2022-05-01T17:20:27.581350+00:00 app[web.3]:     raise value.with_traceback(tb)
2022-05-01T17:20:27.581351+00:00 app[web.3]:   File "/app/templates/landing.html", line 1, in top-level template code
2022-05-01T17:20:27.581351+00:00 app[web.3]:     {% extends 'base.html' %}
2022-05-01T17:20:27.581351+00:00 app[web.3]:   File "/app/templates/base.html", line 52, in top-level template code
2022-05-01T17:20:27.581352+00:00 app[web.3]:     {% block body %}
2022-05-01T17:20:27.581352+00:00 app[web.3]:   File "/app/templates/base.html", line 53, in block "body"
2022-05-01T17:20:27.581352+00:00 app[web.3]:     {% block content %}
2022-05-01T17:20:27.581353+00:00 app[web.3]:   File "/app/templates/landing.html", line 71, in block "content"
2022-05-01T17:20:27.581353+00:00 app[web.3]:     <div class="segment-subtitle mb-5">{{gettext("")}}</div>
2022-05-01T17:20:27.581353+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/jinja2/ext.py", line 156, in gettext
2022-05-01T17:20:27.581354+00:00 app[web.3]:     return rv % variables
2022-05-01T17:20:27.581354+00:00 app[web.3]:   File "/app/.heroku/python/lib/python3.9/site-packages/markupsafe/__init__.py", line 108, in __mod__
2022-05-01T17:20:27.581354+00:00 app[web.3]:     return self.__class__(super().__mod__(arg))
2022-05-01T17:20:27.581355+00:00 app[web.3]: ValueError: unsupported format character '=' (0x3d) at index 256
2022-05-01T17:20:27.584225+00:00 app[web.3]: measure#nginx.service=1.000 request_id=07649262-924d-4a20-90c0-1ae383a370a2
2022-05-01T17:20:27.586254+00:00 app[web.3]:  - - [01/May/2022:10:20:27 -0700] "GET /ru/ HTTP/1.0" 500 290 "https://www.originprotocol.com/zh_Hant/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
2022-05-01T17:20:27.584455+00:00 heroku[router]: at=info method=GET path="/ru/" host=www.originprotocol.com request_id=07649262-924d-4a20-90c0-1ae383a370a2 fwd="68.235.156.111,172.69.70.160" dyno=web.3 connect=0ms service=1000ms status=500 bytes=568 protocol=https
```

**Comment by micahalcorn** [comment]
Resolved by https://github.com/OriginProtocol/origin-website/commit/669421971acac1cb182f0acd2f1f97c342c7c38a ✅
